sudo: required
services: 
  - docker

before_install:
  - docker build -t ppl15/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ppl15/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env" 
  bucket_name: "elasticbeanstalk-ap-south-1-933445339555"
  bucket_path: ".elasticbeanstalk"
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

